### PR TITLE
Replaced Mustache with Handlebars

### PR DESCRIPTION
**Pull request by mattdrose**
I find Mustache to be a bit limiting, mainly because I can't check if a list is empty. Handlebars gives the freedom to use more complicated parsing.

Hopefully it isn't too much trouble for people to convert existing Mustache templates.

### CODE REVIEW

**Comment by darcyclarke** [comment]
Hey @mattdrose can you rebase and squash your commit. This is a good add so I'll merge once that's done.

**Comment by VinSpee** [comment]
I'm considering grunt-dss for a new project, but would love to see this in before I begin. What's the status @darcyclarke?

**Comment by MoOx** [comment]
:+1: for this !

**Comment by darcyclarke** [comment]
+1 Sorry for the wait

**Pull request merged**
